version: '3'

services:
  onlineshop-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433

  onlineshop-api:
    restart: unless-stopped
    build: .
    ports:
      - 3001:80
    links:
      - onlineshop-sql
    depends_on:
      - onlineshop-sql